name: Test-Sense Pipeline

on: [push]

jobs:
  test-sense:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # This ensures we get the full history for accurate diff

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests fastapi uvicorn gitpython networkx transformers torch

    - name: Start Test-Sense Service
      run: |
        python test_sense_service.py &
        sleep 5  # Give the service time to start

    - name: Run Test-Sense Pipeline
      run: |
        python test_sense_runner.py ${{ github.workspace }} ${{ github.sha }}

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test_results.json